# Generated by Django 3.2.2 on 2021-05-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='scedule_date',
            new_name='schedule_date',
        ),
        migrations.AlterField(
            model_name='customers',
            name='claim_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='invoice_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pid_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ref_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ticket_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
